services:
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: golang-gin-boilerplate
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - golang-postgres-network

  golang_app:
    image: golang-gin-boilerplate:1.0
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    networks:
      - golang-postgres-network

networks:
  golang-postgres-network:
    driver: bridge

volumes:
  postgres_data: